### PR TITLE
Add vendored dependencies.

### PR DESCRIPTION
**Pull request by patrickdappollonio**
Re-adding the vendored dependencies.

Signed-off-by: Patrick D'appollonio <dappollonio@hpe.com>

### CODE REVIEW

**Comment by wenlock** [comment]
@patrickdappollonio could you add a small HACKING.md file that explains how you added the vendor?

I'm hoping you used something like `glide install` or `glide update` which should set it up proper from the glide.yaml.   What do you think?

**Comment by patrickdappollonio** [comment]
Yeah no problem, I can add that! 

I actually used [`govendor`](https://github.com/kardianos/govendor) just because I had it installed. Like I explained before, for any Go user out there, the `vendor/` folder doesn't need to specifically tie it to a certain tool. Someone may use `gb`, maybe the upcoming `go tool dep` (which may see the light by the end of the year), or even some people may copy by hand the dependencies.

The rule is: if it's external, you can copy the same path inside the `vendor/` folder. There's no need for an "specific" tool. The tools only provide additional benefits such as pinning an specific version (which, again, you can do it by yourself by just resetting the branch to an specific version). Glide has an extra plus, which is dependency flattening, which is good to avoid dependency loops.

If you want, I can still use glide. Usually `govendor` has a more cleaner approach since you don't need the `glide.yaml` and the `glide.lock` file hanging around your project's root directory, but instead it uses a [`vendor.json` located inside the `vendor/` folder itself](https://github.com/HewlettPackard/terraform-provider-oneview/blob/glide-up/vendor/vendor.json) which can also be used to pin to a specific SHA.

Let me know if you want to go with Glide or keep govendor. I'm fine with both, then we can add a `HACKING.md` to explain how to add new dependencies.

**Comment by patrickdappollonio** [comment]
I added an additional set of changes. I removed the dependencies from travis, which are no longer needed, since they're vendored right here...

The second change is to the dockerfile. Since you're using wget to pull down the terraform original binary, we may run into issues depending on how the docker environment is set. Inside HPE, usually you'll have to pass the HTTP proxy variables inside the dockerfile, but you can omit that part and use your own environment by downloading the file using `ADD` rather than an actual command, then just extract it as needed ([an example is here](https://github.com/patrickdappollonio/alpine-packer/blob/master/Dockerfile) in the dockerfile of my alpine-packer image).

Try building it with this new Dockerfile and let me know! It should have less layer caches.

**Comment by wenlock** [comment]
Great, much cleaner and works for me.   I'm indifferent in the tool we use for vendoring and was more concerned on making it clear what our processes was for getting and keeping up with updates to the plugin repos from terraform.   I was hoping maybe a Makefile or HACKING.md file to describe how a developer should build it and manage vendoring when needed (basically our recommended approach with sample commands).   

Overall, I'm good with this PR, and thank you for getting the `vendor.json` in place.   If we can agree to use govendor then we can nuke `glide.yaml` and have that be our way of doing it.  Your call. 

On my side for HPE I build with this command:

```
docker build -f ./Dockerfile --no-cache \
               --build-arg http_proxy=$http_proxy \
               --build-arg https_proxy=$https_proxy \
               --build-arg no_proxy=$no_proxy .
```

This way it avoids exposing environment dependencies into the Dockerfile, which we should avoid doing.

What do you think of the following changes for this PR:
1. Add a HACKING.md helper file to explain how to update `/vendor` using govendor
2. remove glide.yaml (up to you)
3. move the build line from `.travis.yaml` from `after_success` section to `script:` section, so that it reads:

```
sudo: required

services:
  - docker

language: go

go:
- 1.8

env:
  global:
    - secure: "JJBNOjRJ11XyeuGd+IyVSG+UBn4gvM4j20pG7WVc49FkqJAwkbOEOHKxeqvDQMMPqdnJ4nn0PR+DDHMCifVmBnghiMF6mMlsbxfR8kRjBP7kOjgBkglW4iU4GDAmuxWIWREo3lYI/pc2Ub7mDpCA+nS2ExEpiwzeFhY9skXVDpJxf0uKcQDKHGkV6APdFLalwtcEKeSeZCZvJGMR48cJ725vZ3pW3JgH7a0fKFR2LnmIDKhWU5OL45dewoSu4HGmrC6mxIABf3MLTqItbbSoRhb1voz2iDd7QqXsCIQ9gc2uYYyQybSYi7ohVEh78fmF/zpFfQkN2UPEbidb0SgrJvGmrnX6MN+AT1hhbI6LFuPfCHVbYog6iwkkjo4Ys+uVTx8+LiOTdS+ufVS4Hi8daihuRXI9+3+DBkdF5ZvHDBgxe44oHiK6C52brcVL5/YcG0Q3QnRRpGlaItBttcgTBbZbX7UaJ/Rv2soJxTcrB5pHn7FxWL/zr4B7+XQRbGPWah4WHcEnaIexwcheYeUHVW5pcz6YMgLzOH7btPCiS98240o/0vrxOxv60rDLmWakkZ06stHd9sLYYKDNMsqhTWSNmbzC6n3dmICwRWXlFmywK9eAKpAIN67JgE2E5l/gUgccwh59nvSSj2BNyfG6uvJNGXuxncPJda/4NrV2x5Q="
    - secure: "NGR5vzS4T1dJ/0kbVqFYwW6oThE7JH4UBFBAzEc7vT6h6NANmY1O+6ojRdmSvnTIjN4vxXZzWfhQTLW9T3pMAeEhyjfn2p2T5fFAf381Ch5fu2fuAbCMOm+gCgSg/FAkQ3qCCAzniPv0cHl7c76NvG6wcC+geVDZw6YmwZ6m3DZ8vT1hQLWZggSeFvNmCsYh6NTulKXxjYOmGGkAkfkzSZxHcFOaMhVYEnQrig4tT6DN0Cjeq089R2pyATSFen5eGzo6Othy/lWkZrd0WWBIj9cX49CL7vvzFtodRALdAC7+GxcNYgmJZWfbMFU6ud01VZ/C8BvBqsELkdxqGdlGr/GUXy9wLQfCp2PyfV9qOa6y8qBCVlbcHzO1WNFAORnJpoD9w5r+/50zQ3o2G/lsHv4+WytHjz1CdiGLUxEXDrjp1uGBWoFb+xR9yqfzH2c4wCoGQSBZkbDa8ESABsrNOc9ewsmStFeq4txmfCR/WmkW+Tr7Ylq5h1XXbzn6PnLvzvQ/dDkk9HdInfpfa4wuNm4k6/7/+gp4NxtHHNy6IudFNFG6Yzmap1Z0q00Mzi3DGFqgHupFB/Rv2Cw+40fcchtCF0KXSRD6eAXHH3pNGscY1hekEd7IbC4w9BkLUxb2q/g6fzP/is1ylBovsnoK5zMuADEPkp+AJHBvyM8tuVk="
    - secure: "vb8LigJ62OtLmgkCDsPXrPKdIxpwu4pvTYWjhvHO1gTr2PHEg5cNkXbrcileY8uzsfc1qoIYX9xbteM4Gcu8UO160R4V47dXxSYs8i1FGPQnW1UmXpkEmfPPHLJUB0WesYXfveCypuWk9ydNVoveLEVdm5S57t29xUEx2taANBktuTSEro4cXD49n4uy/EVnZqPOuXc1qzng1RoEX6O2q3x/C+Sa+jaBo/2UtrwloHS25xOoHh4Lwq6bYQIZZfJaitQnbYxm6trcWcTlJH06qRAoRCvFrZkTvaAUvjO/Y2BNlgfbFTfD9mB7DNGK28T5U5Jd7dX7nq3SVVQfdS32xJAaUDG6gt9QvO2gDxe+xnp1745NS/PrBwrDeRiSrv2bubNua+h1bJz6K5D9horkWuL+S9MI4IV4dBADrG4gFqzXQZESO5Zo8SGIkvwz7xzEr1cXRj3Tt73gU0LEvitXHjDuXtmsZYhRfCQqnWf4QQbieQGnUn0lkPtz4pfv17pxvGQ/fiHFq5bBHiKyn8dKMD2Wce8Xbt7pGucQRmUhoPbvET8h/CyiT3QDiQu9qZbiO+vzNbC5yh8FAwx69ehgzRiJ/uWZ5Thoc0gtrWq7lJgVlB6BP7m9zpTN46a2ug4v0oZ7oPJFNgfjwRqnIkILhuGdaP4CyedH344djywe+0c="
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO=mbfrahry/terraform-provider-oneview
script:
  - docker build -f Dockerfile -t $REPO:$COMMIT . 
after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
```

**Comment by wenlock** [comment]
Also, since we don't need wget, sudo, git, make, ... just unzip now, can we change the `Dockerfile` to only apk install this:

```
RUN apk add --update unzip
```

We still have to set proxy with build args, but thats an HPE thing.   

Thanks!

**Comment by patrickdappollonio** [comment]
I would definitely love to see it this way! I'll add the Hacking.md file and then explain in there what's the approach. 

I'll also modify the Dockerfile to remove the extra dependencies. I was unsure if because of development you guys might use some of the other packages.

I'll do an extra step: If you notice, we're still using @mbfrahry's account on Docker Hub to upload the docker image tagged "latest". DCIA has an account which is more generic, and we can remove the secure strings from the `.travis.yml` to add them into the travis CI panel, rather than have them hardcoded here. Since it's just a "testing" feature, we can still benefit from publishing it in an HPE-managed account rather than use Matthew's free space (thanks, Matt! 👍)

We don't even need to tag the image that much, since `latest` is by default, we can use [this approach](https://github.com/patrickdappollonio/alpine-packer/blob/36a1e3b95ee06df170c42fdb1dcdd2eb801eb553/.travis.yml#L9-L13) which only pushes if a) we're merging to the master branch; and b) merge and build are successful. That way we can still use PRs as usual.

Let me know what you think!

**Comment by wenlock** [comment]
Great, i'll wait for your tweaks on the `Dockerfile` and `HACKING.md` but the other changes we should do in another PR, so we can separate the story.  Thanks!

**Comment by patrickdappollonio** [comment]
Will do! I'll let you know when it's ready.

**Comment by patrickdappollonio** [comment]
Alright @wenlock, done. I've also updated the main README to make it more Go-friendly so the setup takes less time (since you don't have to download dependencies any longer, plus, `go get` will do the `git clone` with `go install`).

Let me know what you think!

**Pull request merged**
