### PR TITLE
Add Synergy Support for Logical Interconnect Groups

### PR DESCRIPTION
**Pull request by adarobin**
I am not able to create Logical Interconnect Groups with Terraform as described in #47 

I am working to resolve this issue, though it appears there are multiple fields needed to successfully create a LIG.

### CODE REVIEW

**Comment by adarobin** [comment]
I'm not sure why CI is failing.  The file it is complaining about has been run through gofmt.

**Comment by patrickdappollonio** [comment]
Hello @adarobin,

Can you run this command and tell me if it reports any Go files? 

```
find . -type f -name "*.go" -not -path "./vendor/*" | sed "s|^\./||" | xargs gofmt -l
```

**Comment by adarobin** [comment]
@patrickdappollonio 

```bash
m-c02tv2lthtd7:terraform-provider-oneview adarobin$ find . -type f -name "*.go" -not -path "./vendor/*" | sed "s|^\./||" | xargs gofmt -l
oneview/resource_ethernet_network.go
oneview/resource_fc_network.go
oneview/resource_fcoe_network.go
oneview/resource_network_set.go
```

Interesting that the files listed are not what is in the output from CI as having the error.  I'll fix them up and do another commit.

**Comment by adarobin** [comment]
The only thing I'm not happy with is that I need to go back and manually set `enclosure_indexes` to `[1]` for all of my C7000 enclosures.  I'd like to make `[1]` the default value, but that is not possible in the version of Terraform that this plugin is linked against.

**Comment by adarobin** [comment]
@patrickdappollonio 
Now the files that were listed as needing fixed on my machine are listed in the CI.  It appears to be a difference in gofmt behavior between versions. See https://github.com/golang/go/issues/26228

```bash
m-c02tv2lthtd7:terraform-provider-oneview adarobin$ go version
go version go1.11.2 darwin/amd64
```

**Comment by soodpr** [comment]
> 
> 
> The only thing I'm not happy with is that I need to go back and manually set `enclosure_indexes` to `[1]` for all of my C7000 enclosures. I'd like to make `[1]` the default value, but that is not possible in the version of Terraform that this plugin is linked against.

Hello @adarobin - I agree we we should use latest Terraform version. May be we can take this as an enhancement in future.

**Comment by adarobin** [comment]
@soodpr I tested with API version 600.

**Pull request merged**
