### PR TITLE
Add vendored dependencies.

### PR DESCRIPTION
**Pull request by patrickdappollonio**
This PR adds the latest version of the dependencies into the `vendor/` folder, so there's no need to `go get` them or `glide install` them.

Signed-off-by: Patrick D'appollonio <dappollonio@hpe.com>

### CODE REVIEW

**Comment by wenlock** [comment]
Hey, so what do you think about using glide for vendoring?

**Comment by patrickdappollonio** [comment]
Both glide and in this case `govendor` works. They all use the same approach: use the `vendor/` folder to store stuff. The utility of glide is that you can enable semantic versioning as an approach of "saving" stuff, but with any of the current solutions post `GO15VENDOREXPERIMENT` you'll get the option to pin to an specific SHA.

If you want I can switch it to Glide. Still, the goal for anyone who uses this is to actually not even know if you have to use glide or govendor to manage it. You just "pull it down".

**Comment by wenlock** [comment]
@patrickdappollonio agreed.   OK, so your thinking we should include the whole /vendor folder... I get why that make sense (libs move, etc)... i was thinking we could avoid that in this case to keep the repo small... but I could be convinced otherwise.   Should we move the thoughts into the other PR i submitted and make them happen there?  Maybe after a subsequent PR.

**Comment by patrickdappollonio** [comment]
We can merge yours, then I can update this one, then we can remove the extra steps to build without having to pull down any dependencies since we have them all.

About making sense, the overall goal of Go is to keep your dependencies yours. The mindset is to avoid what happened to the NodeJS community not so long ago with leftpad, where one dev removed a very simple package and because everyone was pulling it down, [it broke thousands of projects](https://www.theregister.co.uk/2016/03/23/npm_left_pad_chaos/).

If you still want to point to the actual dependencies' repo, we can use submodules, but that'll make the project non go-gettable and it will require the extra step of git submodules to work.

And [here's the global thinking in Go about vendoring dependencies](https://blog.gopheracademy.com/advent-2015/vendor-folder/). Hope that helps!

**Comment by wenlock** [comment]
@patrickdappollonio +1 agreed, lets do that.   OK, here's the merge, I'll let you take care of the vendoring part.

**Pull request merged**
